### ISSUE TITLE
provide reefied helper function for fixture creation

### ISSUE THREAD

**Issue by jangalinski** [toolisticon/axon-addons#18]
val fixture = AggregateTestFixture(MyAggregate::class.java)

is so java-ish.

Lets provide

    val fixture = aggregateTestFixture<MyAggregate> {
         // further fixture config
    }

**Comment by zambrovski** [comment]
See: 
* https://github.com/toolisticon/axon-extension-kotlin/issues/3
* https://github.com/toolisticon/axon-extension-kotlin/issues/4
